### ISSUE TITLE
Steps to Version 1

### ISSUE THREAD

**Issue by bfkelsey** [airsonic/airsonic-ui#14]
Here I would like to keep a list to track what needs to be done for an MVP to be developed. This should be in a state where we can ship it with airsonic as an experimental UI.

- [x] Add Logout and improve logout menu to show user name.
- [x] Add Current playing track information to media player bar.
- [ ] Add the ability to queue songs. #12 
- [ ] Add a basic settings page
- [ ] Improve test coverage
- [ ] Improve error handling. Should display errors to user.

**Comment by atecey** [comment]
I'd like to get more involved in this as it's something I want to use myself + I spend all day everyday working with Angular. I've a few questions.

Are yous developing against an actual airsonic backend?
If so do yous have the existing api calls documented anywhere? 
Is there any other documentation I could use to get started?

**Comment by jooola** [comment]
@atecey I you want to build a part of the UI, I suggest you to pick one in the road-map ticket #57 .

Yes we are developing against a real back-end. Since airsonc don't have it's [own API yet](https://airsonic.github.io/docs/api/), we use the [subsonic API](http://www.subsonic.org/pages/api.jsp).
The samples are in XML, but we use JSON.

**Comment by bfkelsey** [comment]
Closing this in favor of #57
